# Generated by Django 6.0 on 2026-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('track_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('popularity', models.IntegerField()),
                ('valence', models.FloatField()),
                ('energy', models.FloatField()),
                ('tempo', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
            ],
        ),
    ]
