# Generated by Django 6.0 on 2026-04-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_spotifytrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningsession',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='dass_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dassresult'),
        ),
        migrations.AlterField(
            model_name='track',
            name='energy',
            field=models.FloatField(default=0.5, help_text='Năng lượng (0.0 - 1.0)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='tempo',
            field=models.FloatField(default=100.0, help_text='Nhịp độ (BPM)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.FloatField(default=0.5, help_text='Độ tích cực (0.0 - 1.0)'),
        ),
    ]
