# Generated by Django 6.0 on 2026-04-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_listeningsession_tracks_track_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listeningsession')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('session', 'track')},
            },
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='tracks',
            field=models.ManyToManyField(related_name='sessions', through='api.SessionTrack', to='api.track'),
        ),
    ]
