# Generated by Django 6.0 on 2026-04-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sessiontrack_listeningsession_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_tracks',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='api.track'),
        ),
    ]
