# Generated by Django 6.0 on 2026-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Cuộc trò chuyện mới', max_length=255),
        ),
    ]
