# Generated by Django 6.0 on 2026-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chatsession_options_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consented',
            field=models.BooleanField(default=False),
        ),
    ]
