# Generated by Django 6.0 on 2026-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_is_consented'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsession',
            name='mood_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='mood_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='total_duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
